version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: rambo-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "rambo_dev"
    volumes:
      - db_data:/var/lib/mysql

  nats:
    image: nats:latest
    container_name: rambo-nats
    ports:
      - "4222:4222"

volumes:
  db_data: